
package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuoteofTheDay", targetNamespace = "http://swanandmokashi.com", wsdlLocation = "http://www.swanandmokashi.com/HomePage/WebServices/QuoteOfTheDay.asmx?WSDL")
public class QuoteofTheDay
    extends Service
{

    private final static URL QUOTEOFTHEDAY_WSDL_LOCATION;
    private final static WebServiceException QUOTEOFTHEDAY_EXCEPTION;
    private final static QName QUOTEOFTHEDAY_QNAME = new QName("http://swanandmokashi.com", "QuoteofTheDay");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.swanandmokashi.com/HomePage/WebServices/QuoteOfTheDay.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUOTEOFTHEDAY_WSDL_LOCATION = url;
        QUOTEOFTHEDAY_EXCEPTION = e;
    }

    public QuoteofTheDay() {
        super(__getWsdlLocation(), QUOTEOFTHEDAY_QNAME);
    }

    public QuoteofTheDay(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUOTEOFTHEDAY_QNAME, features);
    }

    public QuoteofTheDay(URL wsdlLocation) {
        super(wsdlLocation, QUOTEOFTHEDAY_QNAME);
    }

    public QuoteofTheDay(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUOTEOFTHEDAY_QNAME, features);
    }

    public QuoteofTheDay(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuoteofTheDay(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuoteofTheDaySoap
     */
    @WebEndpoint(name = "QuoteofTheDaySoap")
    public QuoteofTheDaySoap getQuoteofTheDaySoap() {
        return super.getPort(new QName("http://swanandmokashi.com", "QuoteofTheDaySoap"), QuoteofTheDaySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuoteofTheDaySoap
     */
    @WebEndpoint(name = "QuoteofTheDaySoap")
    public QuoteofTheDaySoap getQuoteofTheDaySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://swanandmokashi.com", "QuoteofTheDaySoap"), QuoteofTheDaySoap.class, features);
    }

    /**
     * 
     * @return
     *     returns QuoteofTheDaySoap
     */
    @WebEndpoint(name = "QuoteofTheDaySoap12")
    public QuoteofTheDaySoap getQuoteofTheDaySoap12() {
        return super.getPort(new QName("http://swanandmokashi.com", "QuoteofTheDaySoap12"), QuoteofTheDaySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuoteofTheDaySoap
     */
    @WebEndpoint(name = "QuoteofTheDaySoap12")
    public QuoteofTheDaySoap getQuoteofTheDaySoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://swanandmokashi.com", "QuoteofTheDaySoap12"), QuoteofTheDaySoap.class, features);
    }

    /**
     * 
     * @return
     *     returns QuoteofTheDayHttpGet
     */
    @WebEndpoint(name = "QuoteofTheDayHttpGet")
    public QuoteofTheDayHttpGet getQuoteofTheDayHttpGet() {
        return super.getPort(new QName("http://swanandmokashi.com", "QuoteofTheDayHttpGet"), QuoteofTheDayHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuoteofTheDayHttpGet
     */
    @WebEndpoint(name = "QuoteofTheDayHttpGet")
    public QuoteofTheDayHttpGet getQuoteofTheDayHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://swanandmokashi.com", "QuoteofTheDayHttpGet"), QuoteofTheDayHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns QuoteofTheDayHttpPost
     */
    @WebEndpoint(name = "QuoteofTheDayHttpPost")
    public QuoteofTheDayHttpPost getQuoteofTheDayHttpPost() {
        return super.getPort(new QName("http://swanandmokashi.com", "QuoteofTheDayHttpPost"), QuoteofTheDayHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuoteofTheDayHttpPost
     */
    @WebEndpoint(name = "QuoteofTheDayHttpPost")
    public QuoteofTheDayHttpPost getQuoteofTheDayHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://swanandmokashi.com", "QuoteofTheDayHttpPost"), QuoteofTheDayHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUOTEOFTHEDAY_EXCEPTION!= null) {
            throw QUOTEOFTHEDAY_EXCEPTION;
        }
        return QUOTEOFTHEDAY_WSDL_LOCATION;
    }

}
